#!/bin/sh

if [ -z "$@" ]; then
    echo "usage: $0 <file[s]>"
    echo "sets read-only file permission/ownership for fileserver (recursively)"
    echo ""
    echo "(permissions: u+rw,og+rX; owner:fserver:fserver)"
    echo ""
    exit 1
fi

chmod -R u+rw,og+rX "$@"
chown -R fserver.fserver "$@"
