#!/bin/bash
# backup configs

DBG=1

FILES="
/etc
/root
/usr/share/mc
/usr/local/bin
"

# DO NOT WRAP IN QUOTES OR realpath/readlink doesn't work!!!
EXCLUDE="
~/.pcloud
~/backups
*.rar
*.7z
*.tgz *.tar.gz
*.tbz *.tar.bz2
*.tar.xz *txz
*.deb
*.rpm
*.arch
*.pack
*.so
"

#BKDIR=~
BKDIR=.

ARCHIVENAME=configs

MAXSIZE=5M

homedir=`realpath ~`

for i in $EXCLUDE; do
    [ $DBG ] && echo "i: $i"
#    rpath="$(cd -- "$(dirname "$i")" > /dev/null 2>&1 ; pwd -P)"
    [ "$i" ] && {
	rpath=$i
	[ "${i::1}" == "~" ] && {
	    i=`echo "$i" | sed -e "s#^~#$homedir#"`
	    rpath=`realpath $i`
	}
	[ $DBG ] && echo "real path: $rpath"
	[ "$tarexcludes" ] && tarexcludes="$tarexcludes --exclude='$rpath'" || tarexcludes="--exclude='$rpath'"
	[ "$excl" ] && excl="$excl $rpath" || excl="$rpath"
    }
done

[ $DBG ] && {
echo "tarexcludes: $tarexcludes"
echo "excl: $excl"
read -p "Press any key"
}

PREFIX=`uname -n`-`date +%Y-%m-%d`
ARCNAME="$PREFIX-$ARCHIVENAME"
    # see https://unix.stackexchange.com/questions/32845/tar-exclude-doesnt-exclude-why
    # we're doing configurations only, exclude files larger than MAXSIZE
    tar -X<(for i in ${excl}; do echo $i; done) --exclude-from <(find $FILES -size +$MAXSIZE) -czf "$BKDIR/$ARCNAME.tgz" --files-from <(for i in ${FILES}; do echo $i; done)

apt list --installed | gzip >"$BKDIR/$PREFIX-debian-packages.txt.gz"
