#!/bin/sh

debug () {
    echo "FILES     = $FILES"
    echo "FILTERCMD = $FILTERCMD"
    echo "EXECCMD       = $EXECCMD"
}

usage () {
    echo "usage: $0 <args> (see script)"
}

parseArgs () { 
#    echo $#
    for i in "$@"; do
	if [ -z $FILES ]; then
	    FILES="$i"
#	    FILTERCMD="grep '$i'"
	elif [ -z "$FILTERCMD" ]; then
	    FILTERCMD="grep $i"
	else
	    FILTERCMD="$FILTERCMD | grep $i"
	fi
#        echo "($i)";
    done;
#    for i in $*; do
#        echo "(($i))";
#    done
}

parseArgs "$@"



if [ -z "$FILTERCMD" ]; then
    usage
    exit 1
fi

EXECCMD="cat $FILES | $FILTERCMD"
EXECCMD="ls | grep a"
echo ""

$EXECCMD
#cat $FILES | $FILTERCMD

debug

# line with multigrep
