#!/bin/sh

# test multiple diff/patch: apply a series of patches to a base file to get last version

basefile=file.first
tmpfile=file.last.tmp

cat $basefile > $tmpfile

for i in `ls *.diff`; do 
    echo $i; 
    patch $tmpfile $i
done
