#!/bin/sh
#HTTP_PROXY=193.230.219.12:80
HTTP_PROXY=`cat ~/.http_proxy`

echo "using proxy: $HTTP_PROXY"

wget -e http_proxy=$HTTP_PROXY -e robots=off -UMozilla/5.0 --proxy=on -b -r -l 999 -np -nH -k -R "*[DMNS]=*" $@
