#!/bin/sh

FTP_SERVER=ftp.pub.ro/pub/mirrors
FTP_USER=anonymouns
FTP_PASS=
FTP_PATH=/
MNT_POINT=/mnt/ftpfs

if ! [ -d $MNT_POINT ]; then mkdir $MNT_POINT; fi

lufsmount -q "ftpfs://$FTP_USER:$FTP_PASS@$FTP_SERVER" $MNT_POINT

#lufsmount "ftpfs://ktmpyah:dapktmp@ftp.dap.ro" /mnt/ftpfs
#lufsmount "ftpfs://$FTP_USER:$FTP_PASS@ftp.dap.ro" /mnt/ftpfs
