#!/bin/bash

# not great :(
# some directory reading errors?

# format:
# session_name [user@]host:port[/path] [/default_mount_poit] []
HOSTS="
woopy woopy:/

"

usage() {
HLP="
usage: $0 <session> [mount_point]
"
echo "$HLP"
}

if ! [ $@ ]; then usage; exit 1; fi

HOST=$1

FOUND=echo "$HOSTS"|grep -i $HOST
if [ $FOUND ]; then
    [ $DBG ] && echo "found host: $FOUND"
fi

exit

MNT_POINT=/mnt/sshfs-$HOST

FMASK=444
DMASK=555

usage() {
HLP="
usage: $0 <host>
"
echo "$HLP"
}

while [ $# -gt 0 ]; do
  case "$1" in 
    -a | --all ) FIND=.; shift ;;
    -u | --user ) FIND=$2 ; shift 2 ;;
    -c | -p | --command | --process ) FIND=$2 ; shift 2 ;;
    -h* | --h*  ) usage; exit 0 ;;
#   * ) FIND=":.*$1"; shift ;; # "fuzzy"
#   * ) FIND=":$1 ("; shift ;;
   *) if [ -z $hp ]; then hp=$1; elif [ -z $m ]; then $m=$1; fi; break ;;
  esac
done


if ! [ -z $hp ]; then
# user/host
    n=`echo $hp|awk -F@ '{print NF}'` # get num fields
    if [ $n -gt 1 ]; then
	u=`echo "$hp"|awk -F@ '{print $1}'`
	h=`echo "$hp"|awk -F@ '{print $2}'`
    else
	u=`whoami`
	h=$@
    fi

# mount point
    if [ -z $m ]; then m=$h; fi
USERNAME=$u
HOST=$h
MNT_POINT=/mnt/sshfs-$m
fi

if ! [ -d $MNT_POINT ]; then mkdir $MNT_POINT; fi

#OPTS="-C" # compression

sshfs "$USERNAME@$HOST:$MNT_PATH" $MNT_POINT -p $PORT $OPTS

#/usr/bin/lufsd none $MNT_POINT -o fs=sshfs,host=$HOST,USERNAMEname=$USER,password=$PASS,port=$PORT,root=$MNT_PATH,fmask=$FMASK,dmask=$DMASK,quiet

#lufsd none %s -o fs=%s,host=,USERNAMEname=,password=,port=,root=/,uid=,gid=,fmask=,dmask=,channels=,,own_fs,quiet
#lufsmount -q "sshfs://$USERNAME:$PASS@$SERVER" $MNT_POINT
#lufsmount -q "sshfs://$USERNAME:$PASS@$SERVER" $MNT_POINT --fmask=$FMASK --dmask=$DMASK
