#!/bin/sh


# google search
browser=w3m
browser=lynx
browser=links
url="http://www.google.com/search?q="

DBG=no

usage() {
HLP="
usage: $0 [search keyword(s) ..]
options:
  -h		this help
  -n		search news*
  -l		lucky (tm)
  --DBG	DBG

search via search engine (google)
"
    echo "$HLP"
}

while [ $# -gt 0 ]; do
  case "$1" in 
   -h|--help ) usage ; exit 0 ;;
   -n|--news ) shift ;; #***
   -l|--lucky ) LUCKY=1; shift ;;
   --DBG ) DBG=yes; shift ;;
   * ) [ $s ] && s="$s+$1" || s="$1"; shift ;;
  esac
done

MYNAME=`echo $0|awk -F/ '{print $NF}'`

case "$MYNAME" in
    gl ) LUCKY=1 ;;
esac

# create url
url="$url$s"
[ $LUCKY ] && url="$url&btnI="

#c="$browser http://www.google.com/search?q=$@"
cl="$browser $url"

if [ "$DBG" == "yes" ]; then
    echo "string to search: $s"
    echo "command line: $cl"
    read dummy
fi

$cl
