#!/bin/sh

# dns report
browser=w3m
browser=lynx
browser=links
url="http://www.dnsreport.com/tools/dnsreport.ch?domain="

DBG=no

usage() {
HLP="
usage: $0 [search keyword(s) ..]
options:
  -h		this help
  --debug	debug messages

search via search engine (google)
"
    echo "$HLP"
}

while [ $# -gt 0 ]; do
  case "$1" in 
   -h|--help ) usage ; exit 0 ;;
#   -n|--news ) shift ;; #***
#   -l|--lucky ) LUCKY=yes; shift ;;
   --debug ) DBG=yes; shift ;;
   * ) [ $s ] && s="$s+$1" || s="$1"; shift ;;
  esac
done

MYNAME=`echo $0|awk -F/ '{print $NF}'`

#case "$MYNAME" in
#    gl ) LUCKY=yes ;;
#esac

# create url
url="$url$s"
#if [ "$LUCKY" == "yes" ]; then
#    url="$url&btnI="
#fi

#c="$browser http://www.google.com/search?q=$@"
cl="$browser $url"

if [ "$DBG" == "yes" ]; then
    echo "string to search: $s"
    echo "command line: $cl"
    read dummy
fi
$cl

